### ISSUE TITLE
logger 생성 방식 통일

### ISSUE THREAD

**Issue by egg528** [depromeet/amazing3-be#5]
### ⚠️ Issue
- log 생성 방식을 통일하는 건 어떨까 싶어서 조금 알아봤는데요.
- 잘 정리된 글이 있어서 공유드립니다. 한번 확인해보시고 가장 편리한 방식에 대해서 같이 고민해보면 좋을 것 같네요~!
    - [Kotlin + Spring Boot에서 Slf4j 사용하여 로그 찍는 여러 방법들](https://colabear754.tistory.com/150)
    - [baeldung 관련 글](https://www.baeldung.com/kotlin/kotlin-logging-library)

### ✏️ ToDoList
- [ ] logger 객체 생성 방식 통일

**Comment by binary-ho** [comment]
으악 롬복이 안 된다니..
제일 깔끔해 보이는건 팩터리 메서드이긴 한것 같네요.
그럴 일 거의 없겠지만, 로그 생성 방식이 변경되면 그 메서드만 바꾸면 되서 더 깔끔할 것 같네요.

Lombok의 @Slf4j나 @Log4j2 같은 어노테이션 처럼 동작하는 어노테이션을 직접 만드는건 어떨까 찾아봤는데 좀 투머치 인것 같네요 ㅋㅋ

**Comment by binary-ho** [comment]
저희 로그 구현체는 뭐로 하실건가요? 기본 logback 쓰나요 아니면 log4j2쓸까요

**Comment by egg528** [comment]
오! 덕분에 간단하게라도 구현체 비교를 해보게 됐네요! ㅎㅎ
조금 알아보긴 했는데 Log4j2를 사용에서 가장 큰 장점은 AsyncLogger인 것 같은데요
logging에 스레드를 여러게 생성하는 게 좋은 건지, 또 로깅 실패 시 알 수 없을 수도 있다는 점이 조금 걸리긴 하네요

두 분 생각은 어떠신가요?
